version: 2
run:
  timeout: 2m

presets:
  disable:
    - recommended
  enable: []

linters-settings:
  gocyclo:
    min-complexity: 16
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 175
  funlen:
    lines: 80
    statements: 40

linters:
  disable-all: true
  enable: []
  disable:
    - errcheck
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo
        - lll

service:
  golangci-lint-version: 1.64.x


